import { useState } from 'react';
import { AlertCircle, AlignLeft, Calendar, Clock, Link as LinkIcon, Sparkles } from 'lucide-react';
import { Button } from '../ui/Button';
import { PropertyRow } from '../ui/PropertyRow';
import { getTaskStatusBadge } from './tasksUtils';
import type { Task, TaskDetail } from '../../types';

interface TaskDrawerContentProps {
  task: Task | null;
  onClose: () => void;
  onDelegateTask?: (input: { title: string; description: string; tool: string; priority: Task['priority'] }) => Promise<TaskDetail>;
}

const TASK_METADATA_ITEMS = [
  { key: 'priority', label: 'Priority', icon: AlertCircle },
  { key: 'tool', label: 'Tool', icon: LinkIcon },
  { key: 'created', label: 'Created', icon: Calendar },
  { key: 'updated', label: 'Updated', icon: Clock },
] as const;

function getOpenLabel(task: Task): string {
  if (task.url?.includes('docs.google.com/document')) {
    return 'Open in Google Docs';
  }

  if (task.url?.includes('docs.google.com/spreadsheets')) {
    return 'Open in Google Sheets';
  }

  if (task.url?.includes('docs.google.com/presentation')) {
    return 'Open in Google Slides';
  }

  if (task.url?.includes('drive.google.com')) {
    return 'Open in Google Drive';
  }

  if (task.url?.includes('calendar.google.com')) {
    return 'Open in Google Calendar';
  }

  if (task.url?.includes('mail.google.com')) {
    return 'Open in Gmail';
  }

  if (task.url?.includes('notion.so')) {
    return 'Open in Notion';
  }

  if (task.url?.includes('clickup.com')) {
    return 'Open in ClickUp';
  }

  return `Open in ${task.tool}`;
}


function getTaskMetadataValue(task: Task, key: typeof TASK_METADATA_ITEMS[number]['key']): string {
  switch (key) {
    case 'priority':
      return task.priority;
    case 'tool':
      return task.tool;
    case 'created':
      return 'Today, 10:30 AM';
    case 'updated':
      return task.time;
  }
}

export function TaskDrawerContent({ task, onClose, onDelegateTask }: TaskDrawerContentProps): React.JSX.Element {
  const [title, setTitle] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  async function handleCreateTask(): Promise<void> {
    if (!title.trim() || isSubmitting) {
      return;
    }

    setIsSubmitting(true);
    setSubmitError(null);

    try {
      if (!onDelegateTask) {
        throw new Error('Task delegation is unavailable.');
      }
      await onDelegateTask({ title: title.trim(), description: '', tool: 'Crewmate', priority: 'Medium' });
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unable to create task');
    } finally {
      setIsSubmitting(false);
    }
  }

  if (task) {
    return (
      <div className="space-y-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-mono text-muted-foreground bg-secondary px-2 py-1 rounded-md">{task.id}</span>
            {getTaskStatusBadge(task.status)}
            {task.sourceKind === 'delegated' ? (
              <span className="text-[10px] uppercase tracking-wider text-blue-400">Background task</span>
            ) : null}
          </div>
          <h3 className="text-xl font-semibold text-foreground">{task.title}</h3>
        </div>

        <div className="rounded-xl border border-border/50 bg-secondary/20 p-4">
          {TASK_METADATA_ITEMS.map(({ key, label, icon: Icon }) => (
            <PropertyRow key={key} icon={Icon} label={label} value={getTaskMetadataValue(task, key)} />
          ))}
        </div>

        <div className="space-y-2">
          <div className="text-sm font-medium text-foreground flex items-center gap-2">
            <AlignLeft size={16} className="text-muted-foreground" />
            Description
          </div>
          <div className="text-sm text-foreground/90 font-medium leading-relaxed">
            {task.description?.trim() || `This task was automatically generated by the agent during the session. It involves creating a ticket in ${task.tool} and syncing the relevant context from the screen recording.`}
          </div>
        </div>

        <div className="pt-4 border-t border-border flex gap-3">
          <Button 
            variant="primary" 
            className="flex-1"
            onClick={() => task.url ? window.open(task.url, '_blank') : null}
            disabled={!task.url && task.tool !== 'Crewmate'}
          >
            {getOpenLabel(task)}
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="space-y-1.5">
        <label className="text-sm font-medium text-foreground">What should Crewmate do?</label>
        <textarea
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          placeholder={"e.g. Research our top 3 competitors and save a summary to Notion\ne.g. Write a job description for a senior engineer and add it to ClickUp\ne.g. Draft a cold outreach email for our Series A investors"}
          rows={5}
          className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground resize-none"
        />
        <p className="text-xs text-muted-foreground">Crewmate figures out the rest — which agent, which tool, what steps.</p>
      </div>
      {submitError ? (
        <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {submitError}
        </div>
      ) : null}
      <div className="pt-4 flex gap-3">
        <Button
          variant="primary"
          className="flex-1"
          onClick={() => void handleCreateTask()}
          disabled={!title.trim() || isSubmitting}
        >
          {isSubmitting ? 'Starting...' : <><Sparkles size={16} />Start Background Task</>}
        </Button>
        <Button variant="secondary" className="flex-1" onClick={onClose}>
          Cancel
        </Button>
      </div>
    </div>
  );
}
