import React from 'react';
import {AlertCircle, AlignLeft, Calendar, Clock, Link as LinkIcon} from 'lucide-react';
import {Button} from '../ui/Button';
import {getTaskStatusBadge} from './tasksUtils';
import type {Task} from '../../types';

interface TaskDrawerContentProps {
  task: Task | null;
  onClose: () => void;
}

export function TaskDrawerContent({task, onClose}: TaskDrawerContentProps): React.ReactNode {
  if (task) {
    return (
      <div className="space-y-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-mono text-muted-foreground bg-secondary px-2 py-1 rounded-md">{task.id}</span>
            {getTaskStatusBadge(task.status)}
          </div>
          <h3 className="text-xl font-semibold text-foreground">{task.title}</h3>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <div className="text-xs text-muted-foreground flex items-center gap-1.5">
              <AlertCircle size={14} /> Priority
            </div>
            <div className="text-sm font-medium text-foreground">{task.priority}</div>
          </div>
          <div className="space-y-1">
            <div className="text-xs text-muted-foreground flex items-center gap-1.5">
              <LinkIcon size={14} /> Tool
            </div>
            <div className="text-sm font-medium text-foreground">{task.tool}</div>
          </div>
          <div className="space-y-1">
            <div className="text-xs text-muted-foreground flex items-center gap-1.5">
              <Calendar size={14} /> Created
            </div>
            <div className="text-sm font-medium text-foreground">Today, 10:30 AM</div>
          </div>
          <div className="space-y-1">
            <div className="text-xs text-muted-foreground flex items-center gap-1.5">
              <Clock size={14} /> Updated
            </div>
            <div className="text-sm font-medium text-foreground">{task.time}</div>
          </div>
        </div>

        <div className="space-y-2">
          <div className="text-sm font-medium text-foreground flex items-center gap-2">
            <AlignLeft size={16} className="text-muted-foreground" />
            Description
          </div>
          <div className="text-sm text-muted-foreground bg-secondary/50 p-4 rounded-xl border border-border">
            This task was automatically generated by the agent during the session. It involves creating a
            ticket in {task.tool} and syncing the relevant context from the screen recording.
          </div>
        </div>

        <div className="pt-4 border-t border-border flex gap-3">
          <Button variant="primary" className="flex-1">
            Open in {task.tool}
          </Button>
          <Button variant="secondary" className="flex-1">
            View Logs
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="space-y-1.5">
        <label className="text-sm font-medium text-foreground">Task Title</label>
        <input
          type="text"
          placeholder="e.g. Schedule team sync"
          className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground"
        />
      </div>
      <div className="space-y-1.5">
        <label className="text-sm font-medium text-foreground">Description</label>
        <textarea
          placeholder="Add more details..."
          rows={4}
          className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground resize-none"
        ></textarea>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <label className="text-sm font-medium text-foreground">Tool</label>
          <select className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground appearance-none">
            <option>ClickUp</option>
            <option>GitHub</option>
            <option>Notion</option>
            <option>Slack</option>
          </select>
        </div>
        <div className="space-y-1.5">
          <label className="text-sm font-medium text-foreground">Priority</label>
          <select className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground appearance-none">
            <option>Low</option>
            <option>Medium</option>
            <option>High</option>
          </select>
        </div>
      </div>
      <div className="pt-4 flex gap-3">
        <Button variant="primary" className="flex-1" onClick={onClose}>
          Create Task
        </Button>
        <Button variant="secondary" className="flex-1" onClick={onClose}>
          Cancel
        </Button>
      </div>
    </div>
  );
}
