import { useState } from 'react';
import { AlertCircle, AlignLeft, Calendar, Clock, Link as LinkIcon } from 'lucide-react';
import { Button } from '../ui/Button';
import { Select } from '../ui/Select';
import { getTaskStatusBadge } from './tasksUtils';
import type { Task } from '../../types';

const TOOL_OPTIONS = [
  { value: 'ClickUp', label: 'ClickUp' },
  { value: 'GitHub', label: 'GitHub' },
  { value: 'Notion', label: 'Notion' },
  { value: 'Slack', label: 'Slack' },
];

const PRIORITY_OPTIONS = [
  { value: 'Low', label: 'Low' },
  { value: 'Medium', label: 'Medium' },
  { value: 'High', label: 'High' },
];

interface TaskDrawerContentProps {
  task: Task | null;
  onClose: () => void;
  onCreateTask?: (input: { title: string; description: string; tool: string; priority: Task['priority'] }) => Promise<void>;
}

const TASK_METADATA_ITEMS = [
  { key: 'priority', label: 'Priority', icon: AlertCircle },
  { key: 'tool', label: 'Tool', icon: LinkIcon },
  { key: 'created', label: 'Created', icon: Calendar },
  { key: 'updated', label: 'Updated', icon: Clock },
] as const;

function getTaskMetadataValue(task: Task, key: typeof TASK_METADATA_ITEMS[number]['key']): string {
  if (key === 'priority') {
    return task.priority;
  }

  if (key === 'tool') {
    return task.tool;
  }

  if (key === 'created') {
    return 'Today, 10:30 AM';
  }

  return task.time;
}

export function TaskDrawerContent({ task, onClose, onCreateTask }: TaskDrawerContentProps): React.JSX.Element {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [tool, setTool] = useState('ClickUp');
  const [priority, setPriority] = useState<Task['priority']>('Medium');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  async function handleCreateTask(): Promise<void> {
    if (!onCreateTask || !title.trim() || isSubmitting) {
      return;
    }

    setIsSubmitting(true);
    setSubmitError(null);

    try {
      await onCreateTask({
        title: title.trim(),
        description: description.trim(),
        tool,
        priority,
      });
      onClose();
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unable to create task');
    } finally {
      setIsSubmitting(false);
    }
  }

  if (task) {
    return (
      <div className="space-y-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xs font-mono text-muted-foreground bg-secondary px-2 py-1 rounded-md">{task.id}</span>
            {getTaskStatusBadge(task.status)}
          </div>
          <h3 className="text-xl font-semibold text-foreground">{task.title}</h3>
        </div>

        <div className="grid grid-cols-2 gap-4">
          {TASK_METADATA_ITEMS.map(({ key, label, icon: Icon }) => (
            <div key={key} className="space-y-1">
              <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <Icon size={14} />
                {label}
              </div>
              <div className="text-sm font-medium text-foreground">{getTaskMetadataValue(task, key)}</div>
            </div>
          ))}
        </div>

        <div className="space-y-2">
          <div className="text-sm font-medium text-foreground flex items-center gap-2">
            <AlignLeft size={16} className="text-muted-foreground" />
            Description
          </div>
          <div className="text-sm text-muted-foreground bg-secondary/50 p-4 rounded-xl border border-border">
            {task.description?.trim() || `This task was automatically generated by the agent during the session. It involves creating a ticket in ${task.tool} and syncing the relevant context from the screen recording.`}
          </div>
        </div>

        <div className="pt-4 border-t border-border flex gap-3">
          <Button 
            variant="primary" 
            className="flex-1"
            onClick={() => task.url ? window.open(task.url, '_blank') : null}
            disabled={!task.url && task.tool !== 'Crewmate'}
          >
            Open in {task.tool}
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="space-y-1.5">
        <label className="text-sm font-medium text-foreground">Task Title</label>
        <input
          type="text"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          placeholder="e.g. Schedule team sync"
          className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground"
        />
      </div>
      <div className="space-y-1.5">
        <label className="text-sm font-medium text-foreground">Description</label>
        <textarea
          value={description}
          onChange={(event) => setDescription(event.target.value)}
          placeholder="Add more details..."
          rows={4}
          className="w-full bg-secondary border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-ring text-foreground resize-none"
        />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <label className="text-sm font-medium text-foreground">Tool</label>
          <Select
            value={tool}
            onChange={setTool}
            options={TOOL_OPTIONS}
          />
        </div>
        <div className="space-y-1.5">
          <label className="text-sm font-medium text-foreground">Priority</label>
          <Select
            value={priority}
            onChange={(value) => setPriority(value as Task['priority'])}
            options={PRIORITY_OPTIONS}
          />
        </div>
      </div>
      {submitError ? (
        <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {submitError}
        </div>
      ) : null}
      <div className="pt-4 flex gap-3">
        <Button
          variant="primary"
          className="flex-1"
          onClick={() => void handleCreateTask()}
          disabled={!title.trim() || isSubmitting}
        >
          {isSubmitting ? 'Creating...' : 'Create Task'}
        </Button>
        <Button variant="secondary" className="flex-1" onClick={onClose}>
          Cancel
        </Button>
      </div>
    </div>
  );
}
