export const serverConfig = {
  port: Number.parseInt(process.env.PORT ?? '8787', 10),
  corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3000',
  databasePath: process.env.CREWMATE_DB_PATH ?? 'data/crewmate.db',
  encryptionKey: process.env.CREWMATE_ENCRYPTION_KEY ?? '',
  geminiApiKey: process.env.GOOGLE_API_KEY ?? process.env.GEMINI_API_KEY ?? '',
  geminiLiveModel: process.env.GEMINI_LIVE_MODEL ?? 'gemini-2.5-flash-native-audio-preview-12-2025',
  geminiTextModel: process.env.GEMINI_TEXT_MODEL ?? 'gemini-2.5-flash',
  geminiResearchModel: process.env.GEMINI_RESEARCH_MODEL ?? 'gemini-2.5-flash',
  geminiCreativeModel: process.env.GEMINI_CREATIVE_MODEL ?? 'gemini-3-pro-image-preview',
  githubToken: process.env.GITHUB_TOKEN ?? '',
  githubRepoOwner: process.env.GITHUB_REPO_OWNER ?? '',
  githubRepoName: process.env.GITHUB_REPO_NAME ?? '',
  slackBotToken: process.env.SLACK_BOT_TOKEN ?? '',
  slackDefaultChannelId: process.env.SLACK_DEFAULT_CHANNEL_ID ?? '',
  notionToken: process.env.NOTION_TOKEN ?? '',
  notionParentPageId: process.env.NOTION_PARENT_PAGE_ID ?? '',
  clickupToken: process.env.CLICKUP_TOKEN ?? '',
  clickupListId: process.env.CLICKUP_LIST_ID ?? '',
};
